#!/bin/bash

######################################################################################
## Check for modification an start new build process if necessary 
## based on files with git hashes (generated by pull-repos.sh).
######################################################################################

date
echo "Repositories aktualisieren..."
./pull-repos.sh

date

SITE_HASH=`cat ../../site.hash`
SITE_HASH_OLD=`cat ../../site.hash.old`
GLUON_HASH=`cat ../../gluon.hash`
GLUON_HASH_OLD=`cat ../../gluon.hash.old`

NEED_BUILD=0

echo "Site  $SITE_HASH_OLD -> $SITE_HASH"
echo "Gluon $GLUON_HASH_OLD -> $GLUON_HASH"
#echo "NeedBuild: $NEED_BUILD"


if [ "$SITE_HASH" = "$SITE_HASH_OLD" ];then
  NEED_BUILD=0
else
  NEED_BUILD=1
fi

#echo $NEED_BUILD

if [ "$GLUON_HASH" = "$GLUON_HASH_OLD" ];then
  NEED_BUILD=$(($NEED_BUILD + 0))
else
  NEED_BUILD=$(($NEED_BUILD + 1))
fi

echo "NeedBuild: $NEED_BUILD"

if [ $NEED_BUILD -gt 0 ];then
  echo "Build notwendig, starte Build-Prozess..."
  ./make-release.sh

  if [ $? -eq 0 ];then
    echo $GLUON_HASH > ../../gluon.hash.old
    echo $SITE_HASH > ../../site.hash.old
    cp ../../start-build.log ../output/images/.start-build.txt
  fi


else
  echo "Kein Build notwendig. ENDE."
fi

date
exit 0

