#!/bin/bash

######################################################################################
## Check for modification an start new build process if necessary 
## based on files with git hashes (generated by pull-repos.sh).
######################################################################################

date

cd ..
if [ ! -d "site" ]; then
	echo "This script must be called from within the site directory"
	return
fi
cd site 

PATH_LOG=../../.ffwp 
PATH_GLUON=../../gluon
FILE_SITE=$PATH_LOG/site.sha
FILE_GLUON=$PATH_LOG/gluon.sha
FILE_SITE_OLD=$PATH_LOG/site.old.sha
FILE_GLUON_OLD=$PATH_LOG/gluon.old.sha
FILE_LOG=$PATH_LOG/start-build.log

touch $FILE_SITE
touch $FILE_SITE_OLD
touch $FILE_GLUON
touch $FILE_GLUON_OLD

echo "Repositories aktualisieren..."
./pull-repos.sh

date

SITE_HASH=`cat $FILE_SITE`
SITE_HASH_OLD=`cat $FILE_SITE_OLD`
GLUON_HASH=`cat $FILE_GLUON`
GLUON_HASH_OLD=`cat $FILE_GLUON_OLD`
NEED_BUILD=0



echo "Site  $SITE_HASH_OLD -> $SITE_HASH"
echo "Gluon $GLUON_HASH_OLD -> $GLUON_HASH"
#echo "NeedBuild: $NEED_BUILD"


if [ "$SITE_HASH" = "$SITE_HASH_OLD" ];then
  NEED_BUILD=0
else
  NEED_BUILD=1
fi

#echo $NEED_BUILD

if [ "$GLUON_HASH" = "$GLUON_HASH_OLD" ];then
  NEED_BUILD=$(($NEED_BUILD + 0))
else
  NEED_BUILD=$(($NEED_BUILD + 1))
fi

echo "NeedBuild: $NEED_BUILD"

if [ $NEED_BUILD -gt 0 ];then
  echo "Build notwendig, starte Build-Prozess..."
  ./make-release.sh

  if [ $? -eq 0 ];then
    echo $GLUON_HASH > $FILE_GLUON_OLD
    echo $SITE_HASH > $FILE_SITE_OLD
    cp $FILE_LOG $PATH_GLUON/output/images/
  fi


else
  echo "Kein Build notwendig. ENDE."
fi

date
exit 0

