#!/bin/bash

######################################################################################
## Check for modification an start new build process if necessary 
## based on files with git hashes (generated by pull-repos.sh).
######################################################################################

date

cd ..
if [ ! -d "site" ]; then
	echo "This script must be called from within the site directory"
	exit 1
fi
cd site

PATH_GLUON=/home/freifunk/gluon
PATH_FFWP=/home/freifunk/.ffwp
PATH_LOG=$PATH_FFWP/fw/log
FILE_SITE=$PATH_FFWP/fw/site.sha
FILE_GLUON=$PATH_FFWP/fw/gluon.sha
FILE_SITE_OLD=$PATH_FFWP/fw/site.old.sha
FILE_GLUON_OLD=$PATH_FFWP/fw/gluon.old.sha
FILE_LOG=$PATH_LOG/nightly_build.log

if [ ! -f "$FILE_SITE_OLD" ]; then
	echo "1" > $FILE_SITE_OLD
fi

if [ ! -f "$FILE_GLUON_OLD" ]; then
	echo "1" > $FILE_GLUON_OLD
fi

if [ ! -f "$FILE_SITE" ]; then
	echo "0" > $FILE_SITE
fi

if [ ! -f "$FILE_GLUON" ]; then
	echo "0" > $FILE_GLUON
fi

echo "Repositories aktualisieren..."
./pull-repos.sh

date

SITE_HASH=`cat $FILE_SITE`
SITE_HASH_OLD=`cat $FILE_SITE_OLD`
GLUON_HASH=`cat $FILE_GLUON`
GLUON_HASH_OLD=`cat $FILE_GLUON_OLD`
NEED_BUILD=0



echo "Site  $SITE_HASH_OLD -> $SITE_HASH"
echo "Gluon $GLUON_HASH_OLD -> $GLUON_HASH"
#echo "NeedBuild: $NEED_BUILD"


if [ "$SITE_HASH" = "$SITE_HASH_OLD" ];then
  NEED_BUILD=0
else
  NEED_BUILD=1
fi

#echo $NEED_BUILD

if [ "$GLUON_HASH" = "$GLUON_HASH_OLD" ];then
  NEED_BUILD=$(($NEED_BUILD + 0))
else
  NEED_BUILD=$(($NEED_BUILD + 1))
fi

echo "NeedBuild: $NEED_BUILD"

if [ $NEED_BUILD -gt 0 ];then
  echo "Build notwendig, starte Build-Prozess..."
  ./make-release.sh

  if [ $? -eq 0 ];then
    echo $GLUON_HASH > $FILE_GLUON_OLD
    echo $SITE_HASH > $FILE_SITE_OLD
    cp $FILE_LOG $PATH_GLUON/output/images/.build_overview.txt
  fi


else
  echo "Kein Build notwendig. ENDE."
fi

date
exit 0

